# Generated by Django 3.1.1 on 2020-09-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('is_active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_choices',
            fields=[
                ('choice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_right_choice', models.IntegerField()),
                ('choice', models.CharField(max_length=50)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=300)),
                ('userpass', models.CharField(max_length=300)),
                ('regtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_question_answer',
            fields=[
                ('is_right', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_time', models.DateField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question_choices')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.user')),
            ],
        ),
    ]
